# #name: managment
# services:
#   portainer:
#     image: portainer/portainer-ee:lts
#     #container_name: managment_portainer
#     restart: always
#     labels:
#       - "com.centurylinklabs.watchtower.enable=false"
#     ports:
#       - "8000:8000"
#       - "9000:9000"
#     volumes:
#       - portainer_data:/data
#       - /var/run/docker.sock:/var/run/docker.sock

# volumes:
#   portainer_data:



services:
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443