name: managment

services:
  portainer:
    image: portainer/portainer-ee:lts
    container_name: portainer-ee
    network_mode: bridge
    ports:
      - 800:8000
      - 900:9000
    labels:
      io.portainer.accesscontrol.public: "true"